openapi: 3.0.3
info:
  title: Fraud Detection API
  description: API for transaction risk assessment
  version: "1.0"

paths:
  /api/v1/risk-assessment:
    post:
      tags:
        - risk-assessment
      operationId: assessTransactionRisk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RiskAssessmentRequest"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RiskAssessmentResponse"
          description: Risk assessment data returned successfully

  /api/v1/bin/{binNumber}:
    get:
      tags:
        - bin
      operationId: getBinDetails
      parameters:
        - name: binNumber
          in: path
          required: true
          schema:
            type: number
            minimum: 100000
            maximum: 99999999999
            example: 966741047
          description: The Bank Identification Number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBinDetailsResponse'
          description: BIN data was returned successfully
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Invalid BIN format
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: The requested BIN was not found

components:
  schemas:
    RiskAssessmentRequest:
      type: object
      properties:
        binNumber:
          type: string
        amount:
          type: object
          properties:
            value:
              type: number
            currency:
              type: string
        location:
          type: string

    RiskAssessmentResponse:
      type: object
      properties:
        riskScore:
          type: integer
        riskFactors:
          type: array
          items:
            type: object
            properties:
              factorName:
                type: string
              factorDescription:
                type: string

    GetBinDetailsResponse:
      type: object
      properties:
        bin:
          type: number
          description: The Bank Identification Number
        issuerName:
          type: string
          description: The issuer name
        issuerCountry:
          type: object
          description: Country of origin of the issuer.
          properties:
            code:
              type: string
              description: The issuingCountry code in ISO 3166-1 alfa-3 format
              example: POL
            name:
              type: string
              description: The issuingCountry name in human readable format
              example: Poland
          required:
            - code
            - name
        billingCurrency:
          type: string
          description: The default currency of the card in ISO 4217 format.
          example: PLN
        fundingSource:
          type: string
          enum:
            - DEBIT
            - CREDIT
            - PREPAID
            - NONE
          description: The funding source of the card.
        consumerType:
          type: string
          enum:
            - CONSUMER
            - CORPORATE
          description: The type of the customer.
        localUse:
          type: boolean
          description: Flag indicating whether the card may be used outside of the issuingCountry of issuance.
      required:
        - bin
        - customerName
        - consumerType
        - billingCurrency
        - fundingSource
        - accountHolderType
        - localUse

    ErrorResponse:
      type: object
      properties:
        errors:
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
          required:
            - code
            - message
      required:
        - errors