CREATE TABLE TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    BIN VARCHAR(11) NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    RISK_SCORE INT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
);