BEGIN;

ALTER TABLE TRANSACTIONS ALTER COLUMN ID TYPE BIGINT;
ALTER SEQUENCE transactions_id_seq AS BIGINT;
ALTER TABLE TRANSACTIONS ALTER COLUMN ID SET DEFAULT nextval('transactions_id_seq');

COMMIT;
