CREATE TABLE TRANSACTION_RISK_FACTORS
(
    ID uuid PRIMARY KEY,
    TRANSACTION_ID uuid NOT NULL,
    CODE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    SCORE INT NOT NULL,
    WEIGHT FLOAT NOT NULL,
    CONSTRAINT FK_TRANSACTION_RISK_FACTOR FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS (ID)
);